[package]
name = "linkage"
description = "An adaptive typing tutor made with Iced in Rust"
version = "0.3.2"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/linkage-rs/linkage"
categories = ["games"]
keywords = ["typing", "tutor"]

[dependencies]
dirs-next = "2.0"
itertools = "0.14"

rand = "0.10"
serde_json = "1.0"
statrs = "0.18"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.0"
features = ["fs"]

[dependencies.iced]
features = ["tokio", "wgpu", "tiny-skia", "advanced", "canvas", "crisp"]
version = "0.14"
